### ISSUE TITLE
Validation with invalid schema succeeds

### ISSUE THREAD

**Issue by ceving** [furstenheim/is_jsonb_valid#13]
The following returns true:

    select is_jsonb_valid ('{"wurst":"brot"}'::jsonb, 'null'::jsonb);

Although the schema is obviously invalid.

My expectation is, that a validation with an invalid schema throws an exception like this:

    select is_jsonb_valid ('42'::jsonb, 'null'::jsonb);

**Comment by furstenheim** [comment]
Hi Ceving,
You can find the official meta schema for json validators [here](http://json-schema.org/draft-04/schema) 

'{"wurst": "brot"}' is actually a good schema according to that official meta schemas, in that keys that do not belong to the json schema specification are allowed and no constraint is set on those, and there are several implementations that ignore those.

If you want to force your schema to be strict, then I recommend that you validate your validator against a modified meta schema where additional properties are not allowed.

That said, the focus of this library is on the validation of data, since it really is a database extension. Validating the actual json schema would add an overhead that would make no sense, since in the standard use case you would know your json schema before hand.

**Comment by ceving** [comment]
Even small typos in the schema will result in a successful validation. This is definitely the wrong default for any kind of validation. A validation needs to be a white list and not a black list. Seems to me that JSON schema validation is broken by design.

### Example
Doorman: "Hello guest! What is your name?"
Guest: "My name is Mephisto."
Doorman: "I can not find your name on my list. Oh wait! I got the wrong list. Hmm... if I have the wrong list, I do not care anymore. Come in."
Guest: "Hello Margarete!"

**Comment by furstenheim** [comment]
Hi ceving,
As I mentioned, the issue has an easy fix on client code. Fetch the meta
schema and set additional properties to false. Then validate your schema
with the modified meta schema.

As for broken by design, I dunno the specifics, but backwards compatibility
across drafts is probably a good reason

**Comment by ceving** [comment]
I do not think the fix is easy, because the schema you have referenced is quite outdated. The current schema is this:

https://json-schema.org/specification-links.html#2020-12

And with the current schema the fix would not work, because `is_jsonb_valid` is not able to use the schema even in the "unfixed" state:

~~~
select is_jsonb_valid ('
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://json-schema.org/draft/2020-12/schema",
    "$vocabulary": {
        "https://json-schema.org/draft/2020-12/vocab/core": true,
        "https://json-schema.org/draft/2020-12/vocab/applicator": true,
        "https://json-schema.org/draft/2020-12/vocab/unevaluated": true,
        "https://json-schema.org/draft/2020-12/vocab/validation": true,
        "https://json-schema.org/draft/2020-12/vocab/meta-data": true,
        "https://json-schema.org/draft/2020-12/vocab/format-annotation": true,
        "https://json-schema.org/draft/2020-12/vocab/content": true
    },
    "$dynamicAnchor": "meta",

    "title": "Core and Validation specifications meta-schema",
    "allOf": [
        {"$ref": "meta/core"},
        {"$ref": "meta/applicator"},
        {"$ref": "meta/unevaluated"},
        {"$ref": "meta/validation"},
        {"$ref": "meta/meta-data"},
        {"$ref": "meta/format-annotation"},
        {"$ref": "meta/content"}
    ],
    "type": ["object", "boolean"],
    "$comment": "This meta-schema also defines keywords that have appeared in previous drafts in order to prevent incompatible extensions as they remain in common use.",
    "properties": {
        "definitions": {
            "$comment": "\"definitions\" has been replaced by \"$defs\".",
            "type": "object",
            "additionalProperties": { "$dynamicRef": "#meta" },
            "deprecated": true,
            "default": {}
        },
        "dependencies": {
            "$comment": "\"dependencies\" has been split and replaced by \"dependentSchemas\" and \"dependentRequired\" in order to serve their differing semantics.",
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    { "$dynamicRef": "#meta" },
                    { "$ref": "meta/validation#/$defs/stringArray" }
                ]
            },
            "deprecated": true,
            "default": {}
        },
        "$recursiveAnchor": {
            "$comment": "\"$recursiveAnchor\" has been replaced by \"$dynamicAnchor\".",
            "$ref": "meta/core#/$defs/anchorString",
            "deprecated": true
        },
        "$recursiveRef": {
            "$comment": "\"$recursiveRef\" has been replaced by \"$dynamicRef\".",
            "$ref": "meta/core#/$defs/uriReferenceString",
            "deprecated": true
        }
    }
}
'::jsonb, '{}'::jsonb);
~~~

This throws the error.

> $ref must be anchored at root
